# Generated by Django 3.2.7 on 2021-10-11 22:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20211011_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_likes',
            new_name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
